server:
  port: 8040
spring:
#  jpa:
#    generate-ddl: true
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      naming:
#        implicit-strategy: com.imooc.security.rbac.repository.support.ImoocImplicitNamingStrategy
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/xunwu?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: cai552200
#    max-active: 100
#    min-idle: 10
#    min-evictable-idle-time-millis: 1800000
#    test-on-borrow: true
#    test-on-return: true
#    test-while-idle: true
#    validation-query: select 1
  application:
    name: gateway

#  spring.security.user.name=admin
#  spring.security.user.password=123456
#  security:
#    user:
#      name: 111
#      password: 222
  security:
    oauth2:
      jwt:
        colin:
          keyUri: http://localhost:7070/oauth/token_key
          clientId: gateway
          clientSecret: 123456
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: auth_route
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user_route
          uri: lb://user-center
          predicates:
            - Path=/users/**
          filters:
            - CreditFilter
        - id: content_route
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/**
        - id: after_route
          uri: lb://user-center
          predicates:
            # 当且仅当请求时间的时间After配置的时间时，才会转发到用户微服务
            - After=2030-01-20T17:42:47.789-07:00[America/Denver]
            - TimeBetween=上午9:00, 下午5:00
          filters:
            - AddRequestHeader=X-Request-Foo, Bar, Authorization
            - PreLog=a,b
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace
#imooc:
#  security:
#    oauth2:
#      clients[0]:
#        clientId: imooc
#        clientSecret: imoocsecret
#      clients[1]:
#        clientId: test
#        clientSecret: test
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
